using System;
using MentorBilling.Settings.SpecialSettingsTypes;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MentorBilling.Settings
{
    public class ProgramSettings
    {
        #region Properties
#pragma warning disable IDE1006 // Naming Styles
        /// <summary>
        /// the useSellerControl property
        /// </summary>
        protected Boolean useSellerControl { get; set; } = false;
        /// <summary>
        /// the countryISO property
        /// </summary>
        protected SpecialSettingsEnums.CountryISOType countryISO { get; set; } = SpecialSettingsEnums.CountryISOType.ISO2;
        /// <summary>
        /// the countryName property
        /// </summary>
        protected SpecialSettingsEnums.CountryName countryName { get; set; } = SpecialSettingsEnums.CountryName.RO;
        /// <summary>
        /// the autogenerateDocumentNumbers property
        /// </summary>
        protected Boolean autogenerateDocumentNumber { get; set; } = false;
        /// <summary>
        /// the autogenerateDocumentSeries property
        /// </summary>
        protected Boolean autogenerateDocumentSeries { get; set; } = false;
        /// <summary>
        /// the autogenerateNoticeNumber property
        /// </summary>
        protected Boolean autogenerateNoticeNumber { get; set; } = false;
#pragma warning restore IDE1006 // Naming Styles
        #endregion
    }
}
