using System;
using MentorBilling.Settings.SpecialSettingsTypes;

namespace MentorBilling.Settings
{
    public class ProgramSettings
    {
        #region Properties
#pragma warning disable IDE1006 // Naming Styles
        /// <summary>
        /// the useSellerControl property
        /// </summary>
        protected Boolean useSellerControl { get; set; } = false;
        /// <summary>
        /// the countryISO property
        /// </summary>
        protected SpecialSettingsEnums.CountryISOType countryISO { get; set; } = SpecialSettingsEnums.CountryISOType.ISO2;
        /// <summary>
        /// the countryName property
        /// </summary>
        protected SpecialSettingsEnums.CountryName countryName { get; set; } = SpecialSettingsEnums.CountryName.RO;
        /// <summary>
        /// the useBuyerControl property
        /// </summary>
        protected Boolean useBuyerControl { get; set; } = false;
        /// <summary>
        /// the autogenerateDocumentNumbers property
        /// </summary>
        protected Boolean autogenerateDocumentNumber { get; set; } = false;
        /// <summary>
        /// the autogenerateDocumentSeries property
        /// </summary>
        protected Boolean autogenerateDocumentSeries { get; set; } = false;
        /// <summary>
        /// the autogenerateNoticeNumber property
        /// </summary>
        protected Boolean autogenerateNoticeNumber { get; set; } = false;
        /// <summary>
        /// the permitInvoicesOutsideCurrentMonth property
        /// </summary>
        protected Boolean permitInvoicesOutsideCurrentMonth { get; set; } = false;
        /// <summary>
        /// the permitInvoiceInMonthsPrior property
        /// </summary>
        protected Boolean permitInvoiceInMonthsPrior { get; set; } = false;
        /// <summary>
        /// the permitInvoiceInFollowingMonths
        /// </summary>
        protected Boolean permitInvoiceInMonthsFollowing { get; set; } = false;
        /// <summary>
        /// <br>the numberOfMonthPrior property</br>
        /// <br>is linked to the permitInvoiceInMonthsPrior property and represents the maximum number of months for which the setting is viable </br>
        /// </summary>
        protected Int32 numberOfMonthsPrior { get; set; } = 0;
        /// <summary>
        /// <br>the numberOfMonthsFollowing property</br>
        /// <br>is linked to the permitInvoiceInMonthsFollowing property and represents the maximum number of months for which the setting is viable</br>
        /// </summary>
        protected Int32 numberOfMonthsFollowing { get; set; } = 0;
        /// <summary>
        /// the userProductsControl property
        /// </summary>
        protected Boolean useProductControl { get; set; } = false;
        /// <summary>
        /// the searchProductsByCode property
        /// </summary>
        protected Boolean searchProductsByCode { get; set; } = false;
        /// <summary>
        /// the useBarcode property
        /// </summary>
        protected Boolean useBarcode { get; set; } = false;
        /// <summary>
        /// the eanCode property
        /// </summary>
        protected SpecialSettingsEnums.EANCodes eanCode { get; set; } = SpecialSettingsEnums.EANCodes.EAN13;
        /// <summary>
        /// the default VAT Rate 
        /// </summary>
        protected Int64 defaultVATRate { get; set; } = 1;
        /// <summary>
        /// the default VAT in the Price
        /// </summary>
        protected Boolean vatInPrice { get; set; } = true;
        /// <summary>
        /// the default value of the rounding point for display purpouses only
        /// </summary>
        protected Int32 roundAt { get; set; } = 2;
        /// <summary>
        /// the default value of the rounding Mode
        /// </summary>
        protected SpecialSettingsEnums.RoundingMode roundingMode { get; set; } = SpecialSettingsEnums.RoundingMode.Default;
#pragma warning restore IDE1006 // Naming Styles
        #endregion

        #region Callers
        /// <summary>
        /// this function will return the value of the object
        /// </summary>
        protected ProgramSettings Value
        {
            get => this;
        }
        #endregion
    }
}
